name: Azure Resource Group Cleanup

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set Azure subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: List and delete resource groups
        run: |
          rg_list = $(az group list --query "[?starts_with(name, 'vkuma344')].name" -o tsv)
          for rg_name in $rg_list; do
            echo "Deleting resource groups"
            az group delete --name $rg_name --yes --no-wait
          done
      
