name: Azure Resource Group Cleanup

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Set Azure subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: List and delete resource groups
        id: delete_groups
        run: |
          set -e
          rg_list=$(az group list --query "[].name" -o tsv)
          if [ -z "$rg_list" ]; then
            echo "No resource groups found to delete." > summary.md
          else
            echo "Deleted the following resource groups:" > summary.md
            for rg_name in $rg_list; do
              echo "Deleting resource group: $rg_name"
              az group delete --name $rg_name --yes --no-wait
              echo "- $rg_name" >> summary.md
            done
          fi
          cat summary.md
          
      - name: Print summary
        if: always()
        run: |
          echo "## Resource Group Cleanup Summary" >> $GITHUB_STEP_SUMMARY
          cat summary.md >> $GITHUB_STEP_SUMMARY
          
      - name: Check for errors
        if: failure()
        run: echo "There was an error in the previous steps."
      
